Import Debian changes 2.8.2-2
dkms (2.8.2-2) unstable; urgency=medium

  [ Gianfranco Costamagna ]
  * Tweak previous patch to do bash string comparison (Closes: #956245)
    thanks Thorsten Glaser for the reminder!

  [ Andreas Beckmann ]
  * use /etc/dkms/no-autoinstall as flag file to disable autoinstall
  * improve dkms-autopkgtest (Closes: #959910)

  [ Seth Forshee ]
  * Cherry-pick upstream fix for dkms failure with signed kernel modules
    - debian/patches/885f8275aa65fb11be1e17bc28a0b0ea734dc585.patch:

diff --git a/debian/scripts/dkms-autopkgtest b/debian/scripts/dkms-autopkgtest
--- a/debian/scripts/dkms-autopkgtest
+++ b/debian/scripts/dkms-autopkgtest
@@ -4,43 +4,30 @@
 # Copyright: (C) 2014 Canonical Ltd.
 set -eu
 
+result=0
+
 run_pkg() {
     pkg="$1"
-    tmpfile=$(mktemp)
 
-    echo "I: removing binary package $pkg, to get clean state"
+    echo "I: Removing binary package $pkg, to get clean state"
     export DEBIAN_FRONTEND=noninteractive
     apt-get purge -yq $pkg </dev/null 2>&1 >/dev/null || true
 
     echo "I: Installing binary package $pkg"
     export DEBIAN_FRONTEND=noninteractive
     RC=0
-    apt-get install -yq $pkg </dev/null 2>&1 >"$tmpfile" || RC=$?
-    cat "$tmpfile"
+    apt-get install -yq $pkg </dev/null 2>&1 || RC=$?
+    if [ "$RC" -ne 0 ]; then
+        echo "E: Package $pkg failed to install" >&2
+        exit 1
+    fi
+
+    # Try and remove dkms to spot packages which miss a dkms dependency
+    dpkg --remove dkms || true
 
     if ! dkms_conf=$(dpkg -L $pkg | grep 'dkms.conf$'); then
         echo "I: Package $pkg has no dkms.conf, skipping"
         return
-    fi
-
-    # Do not continue if dkms build was skipped due to BUILD_EXCLUSIVE
-    # directive
-    excluded=0
-    grep -q "BUILD_EXCLUSIVE" "$tmpfile" && excluded=1
-    rm "$tmpfile"
-    if [ "$excluded" -eq 1 ]; then
-	    echo "I: Package $pkg excluded by BUILD_EXCLUSIVE directive, skipping"
-	    return
-    fi
-
-    # collect build logs as artifacts
-    if [ -d /var/lib/dkms ]; then
-        (cd /var/lib/dkms; find -name "make.log" -print0 | xargs -0 tar c) > "$ADT_ARTIFACTS/$pkg-make-logs.tar"
-    fi
-
-    if [ "$RC" -ne 0 ]; then
-        echo "E: Package $pkg failed to install" >&2
-        exit 1
     fi
 
     echo "I: Testing binary package $pkg"
@@ -48,26 +35,57 @@ run_pkg() {
     dkms_pkg=$(bash -c ". $dkms_conf; echo \$PACKAGE_NAME" 2>/dev/null)
     dkms_ver=$(bash -c ". $dkms_conf; echo \$PACKAGE_VERSION" 2>/dev/null)
 
-    echo "I: Testing if $dkms_pkg modules are correctly installed"
-    dkmsstatus="$(dkms status $dkms_pkg)"
-    if [ -z "$dkmsstatus" ]; then
-        echo "E: dkms status output is empty!" >&2
-        exit 1
-    fi
-    echo "$dkmsstatus"
+    for k in /lib/modules/*/build
+    do
+        test -d "$k" || continue
+        kver="${k%/build}"
+        kver="${kver#/lib/modules/}"
 
-    if grep -q "Good news! Module version $dkms_ver" /var/log/apt/term.log; then
-        tail -n 50 /var/log/apt/term.log
-        if ! echo "$dkmsstatus" | grep -q "installed"; then
-            echo "E: not installed" >&2
-            exit 1
+        echo "I: Trying to build $dkms_pkg/$dkms_ver for $kver"
+        res=0
+        dkms build -m "$dkms_pkg" -v "$dkms_ver" -k "$kver" || res=$?
+
+        if [ "$res" = 9 ]; then
+            echo "I: $dkms_pkg/$dkms_ver is not supported on $kver (BUILD_EXCLUSIVE directive), skipping"
+            continue
+	fi
+
+        if [ "$res" != 0 ]; then
+            echo "E: $dkms_pkg/$dkms_ver failed to build for $kver" >&2
+            makelog="/var/lib/dkms/$dkms_pkg/$dkms_ver/build/make.log"
+            echo "========== $makelog ==========" >&2
+            cat "$makelog" >&2 || true
+            echo "====================" >&2
+            result=1
+            continue
         fi
-        exit 0
-    fi
 
-    if ! echo "$dkmsstatus" | grep -q "installed$"; then
-        echo "E: not installed" >&2
-        exit 1
+        if ! dkms install -m "$dkms_pkg" -v "$dkms_ver" -k "$kver" ; then
+            echo "E: $dkms_pkg/$dkms_ver failed to install for $kver" >&2
+            result=1
+            continue
+        fi
+
+        echo "I: Testing if $dkms_pkg modules are correctly installed"
+        dkmsstatus="$(dkms status $dkms_pkg -k $kver)"
+        echo "$dkmsstatus"
+        if [ -z "$dkmsstatus" ]; then
+            echo "E: dkms status output is empty!" >&2
+            result=1
+            continue
+        fi
+
+        if ! echo "$dkmsstatus" | grep -q "installed$"; then
+            echo "E: not installed" >&2
+            result=1
+            continue
+        fi
+
+    done
+
+    # collect build logs as artifacts
+    if [ -d /var/lib/dkms ]; then
+        (cd /var/lib/dkms; find -name "make.log" -print0 | xargs -r -0 tar cv) > "$AUTOPKGTEST_ARTIFACTS/$pkg-make-logs.tar"
     fi
 
     # skip modprobing for now; this fails too often (needs particular
@@ -83,8 +101,11 @@ run_pkg() {
     # done
 }
 
-# Try and remove dkms to spot packages which miss a dkms dependency
-dpkg --remove dkms || true
+# Do not (fail to) build the modules upon linux-header-* and *-dkms package
+# installation, which can cause apt-get to fail. We will do this later with
+# improved error reporting.
+# (This only works if the *-dkms package is not yet installed.)
+touch /etc/dkms/no-autoinstall
 
 for pkg in $(awk '/^Package:/ { print $2 }' debian/control | grep "\-dkms$"); do
     # package might be arch: restriction or udeb etc.
@@ -94,3 +115,5 @@ for pkg in $(awk '/^Package:/ { print $2 }' debian/control | grep "\-dkms$"); do
     fi
     run_pkg $pkg
 done
+
+exit $result
